version: '3.8'

services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_DB: wakeup
      POSTGRES_USER: wakeup
      POSTGRES_PASSWORD: wakeup
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - wakeup-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
    #   DATABASE_URL: postgres://postgres:example@db:5432/wakeup
    ports:
      - '3010:3010'
    depends_on:
      - db
    networks:
      - wakeup-network

networks:
  wakeup-network:
    driver: bridge

volumes:
  pg_data:
